# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-frontend:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12.0
    environment:
      CI: false
    working_directory: ~/repo/itc-helper-frontend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      # - store_artifacts:
      #     path: ~/repo/velog-frontend/build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - velog-frontend/build
  deploy-frontend:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo/itc-helper-frontend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run: sudo pip install awscli
      - run: aws s3 sync ./build s3://itc-helper.dguri.io/
      - run: aws cloudfront create-invalidation --distribution-id E165QUCR4GAWMG --paths / /index.html /error.html /service-worker.js /manifest.json /favicon.ico
  deploy-backend:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo/itc-helper-backend
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-backend-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-backend-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-ssr-dependencies-{{ checksum "package.json" }}
      - run: yarn deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: master
      - deploy-frontend:
          filters:
            branches:
              only: master
          requires:
            - build-frontend
      - deploy-backend:
          filters:
            branches:
              only: master
