service:
  name: api-itc-helper

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  profile: ${env:AWS_PROFILE}
  environment:
    SESSION_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-session
    ACCESS_TOKEN_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-access-token
    REFRESH_TOKEN_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-refresh-token
    AUTHORIZATION_CODE_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-authorization-code
    USER_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-user
    SUBJECT_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-subject
    REPORT_DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-report
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateTable
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:*'
    - Effect: Allow
      Action:
        - ses:SendMail
      Resource: 'arn:aws:ses:${opt:region, self:provider.region}:*:*'
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: 'arn:aws:ses:${opt:region, self:provider.region}:*:*'
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: 'arn:aws:sqs:${opt:region, self:provider.region}:*:*'

functions:
  api:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: '*'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

custom:
  apigwBinary:
    types: #list of mime-types
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'
  customDomain:
    domainName: api.itc-helper.dguri.io
    certificateName: api.itc-helper.dguri.io
    createRoute53Record: true
    endpointType: 'regional'
